### ISSUE TITLE
GreenGrass Secret Manager Console: short issue description

### ISSUE THREAD

**Issue by aemson** [aws-greengrass/aws-greengrass-secret-manager#72]
**Describe the bug**
When trying to add secret to greengrass group in the dropdown it only shows the same 10 secret manager items again and again when scrolling. (NB: Group role has permission to access secret manager )

**To Reproduce**
AWS IoT -> GreenGrass v1 -> Groups -> GroupName -> Resources -> Secrets -> Add

**Expected behavior**
The drop down list of the secret manager item names should have all the secret items in secret manager

**Actual behavior**
It shows around 10 entries from secret manager and on scrolling the same 10 repeats forever -

**Environment**
 - All (PROD, TEST, DEV)
 - GreenGrass Version: v1

E.g. what is the impact of the bug?
Have to add the secret via CLI, but in that we need to be careful as an update will override existing configurations.

**Comment by MikeDombo** [comment]
This repository is for Greengrass V2 only.  All new development must be done using Greengrass V2; Greengrass V1 will not be supported after June 2023 - https://docs.aws.amazon.com/greengrass/v1/developerguide/maintenance-policy.html

**Comment by MikeDombo** [comment]
Please contact AWS support for further assistance.
