### ISSUE TITLE
Partial ARN is not allowed by VALID_SECRET_ARN_PATTERN 

### ISSUE THREAD

**Issue by AntonBy** [aws-greengrass/aws-greengrass-secret-manager#78]
https://github.com/aws-greengrass/aws-greengrass-secret-manager/blob/5ee68d10d72df4012c35dc7b7d0cbbfb2b251d25/src/main/java/com/aws/greengrass/secretmanager/SecretManager.java#L59-L61

This pattern allows to use only FullARN but the documentation says about 2 possible options: 
https://docs.aws.amazon.com/greengrass/v2/developerguide/secret-manager-component.html?icmpid=docs_gg_console#secret-manager-component-log-file 

>arn
The ARN of the secret to deploy. The ARN of the secret can either be a full ARN or a partial ARN. We recommend that you specify a complete ARN rather than a partial ARN. For more information, see [Finding a secret from a partial ARN](https://docs.aws.amazon.com/secretsmanager/latest/userguide/troubleshoot.html#ARN_secretnamehyphen). The following is an example of a full ARN and a partial ARN: 
> * Full ARN: arn:aws:secretsmanager:us-east-2:111122223333:secret:SecretName-abcdef
> * Partial ARN: arn:aws:secretsmanager:us-east-2:111122223333:secret:SecretName

ComponentVersion: 2.1.7

**Comment by alter-mage** [comment]
Thanks for bringing this to our attention!
It looks like this is a bug for secrets which do not include a `-` in their name. We will get a fix out for this pronto.

**Comment by alter-mage** [comment]
This issue has been fixed in #79. We will release it in our next release cycle, which I do not have an ETA yet. Please let us know if you have any more questions.

Cheers!
